# Generated by Django 2.1.7 on 2025-06-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attack_type',
            field=models.CharField(default='MITM', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
