# Generated by Django 2.1.7 on 2025-06-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attackapp', '0002_auto_20250629_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='user',
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='destination_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='protocol',
            field=models.CharField(default='TCP', max_length=10),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='session_hijack_prediction',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='source_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='tcp_flags',
            field=models.CharField(default='SYN', max_length=20),
        ),
        migrations.AddField(
            model_name='predictionresult',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='destination_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='duration_sec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='mitm_prediction',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='model_name',
            field=models.CharField(default='ANN', max_length=20),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='packet_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='session_id',
            field=models.CharField(default='S-0000', max_length=50),
        ),
        migrations.AlterField(
            model_name='predictionresult',
            name='source_port',
            field=models.IntegerField(default=0),
        ),
    ]
