# Generated by Django 2.1.7 on 2025-06-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attackapp', '0003_auto_20250629_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='web_attack_type',
            field=models.CharField(default='MITM', max_length=100),
        ),
    ]
